import { BarChart3, Building2, FileText, Globe2, Scale, Users, Zap } from 'lucide-react';

export const services = [
  { slug: 'business-start-ups', title: 'Business Start-Ups', icon: Building2, iconName: 'Building2', shortDescription: 'Practical guidance to turn your business idea into a properly structured and compliant organisation.', fullDescription: 'We help founders establish sound accounting and compliance foundations from the start.', benefits: ['Clear setup guidance', 'Practical compliance support'], targetClients: 'New founders and growing start-ups.', relatedFactSheets: ['Starting Up in Business'] },
  { slug: 'accounts-compliance', title: 'Accounts & Compliance', icon: FileText, iconName: 'FileText', shortDescription: 'Accurate accounts preparation, statutory books and filing support that keeps obligations under control.', fullDescription: 'Accurate accounts and organised filing support help you stay informed and compliant.', benefits: ['Organised records', 'Timely filing support'], targetClients: 'Companies, partnerships, and sole traders.', relatedFactSheets: ['General Business'] },
  { slug: 'taxation', title: 'Taxation', icon: Scale, iconName: 'Scale', shortDescription: 'Careful tax planning and compliance support designed to help you meet your obligations efficiently.', fullDescription: 'Practical tax planning and compliance support shaped around your circumstances.', benefits: ['Plain-English guidance', 'Tax-efficiency reviews'], targetClients: 'Individuals and businesses with tax obligations.', relatedFactSheets: ['Personal Tax', 'Corporate and Business Tax'] },
  { slug: 'support-services', title: 'Support Services', icon: Users, iconName: 'Users', shortDescription: 'Flexible accounting and administrative support that complements your knowledge and helps you grow.', fullDescription: 'Flexible ongoing support keeps financial administration manageable as your organisation develops.', benefits: ['Responsive support', 'Reduced administration'], targetClients: 'Businesses that need an experienced finance partner.', relatedFactSheets: ['General Business'] },
  { slug: 'business-process-outsourcing', title: 'Business Process Outsourcing', icon: Zap, iconName: 'Zap', shortDescription: 'Reliable outsourced financial and administrative processes that reduce workload and improve efficiency.', fullDescription: 'Outsourced processes can give your team reliable routines without adding internal workload.', benefits: ['Reliable processes', 'Improved efficiency'], targetClients: 'Organisations ready to outsource selected finance tasks.', relatedFactSheets: ['General Business'] },
  { slug: 'consultancy-systems-advice', title: 'Consultancy & Systems Advice', icon: BarChart3, iconName: 'BarChart3', shortDescription: 'Personalised consultancy and systems guidance built around your goals, processes and challenges.', fullDescription: 'We review systems and processes, then recommend practical improvements that support better decisions.', benefits: ['Systems review', 'Actionable recommendations'], targetClients: 'Owners and teams reviewing their finance systems.', relatedFactSheets: ['ICT', 'General Business'] },
  { slug: 'uk-visa-accounting', title: 'UK Visa Accounting', icon: Globe2, iconName: 'Globe2', shortDescription: 'Customised accounting, forecasting and financial documentation support for eligible UK visa requirements.', fullDescription: 'Careful forecasting and documentation support can help eligible applicants prepare financial information.', benefits: ['Structured forecasts', 'Documentation support'], targetClients: 'Eligible UK business and visa applicants.', relatedFactSheets: ['Specialist Areas'] },
];

export const serviceDetails = {
  included: ['A clear review of your requirements', 'Practical advice in plain English', 'Accurate, well-organised documentation', 'Responsive support when questions arise', 'A considered next step for your organisation'],
  targetClients: 'Individuals, founders, established companies and organisations looking for a dependable accounting partner.',
  faqs: ['How do I get started?', 'What information will you need?', 'Can this service grow with my business?'],
};
